---
layout: post
title: Promise
tags: [JS, Promise]
---

## Promise
State: pending -> fulfilled or rejected
Producer vs Consumer

### 1. Producer
resolve()
```
// when new Promise is create, the executor runs automatically
const promise = new Promise((resolve, reject) => {
  // doing some heavy work (network, read files) 
  console.log("doing something...");
  setTimeout(() => {
    resolve("wyjeon");
  }, 2000);
});
```
<br/>

reject()
```
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error("no network"));
  }, 2000);
});
```
<br/>

### 2. Consumers: then, catch, finally
```
promise
  .then((value) => { 
    console.log(value); // wyjeon
  })
  .catch(error => {
    console.log(error);
  })
  .finally(() => {
    console.log("finally);  
  });
```
<br/>

### 3. Promise chaining
```
const fecthNumber = new Promise((resolve, reject) => {
  setTimeout(() => resolve(1), 1000); // 1, 1sec
});

fecthNumber
.then(num => num * 2) // 2
.then(num => num * 3) // 6
.then(num => {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(num-1), 1000); // 5 ,1sec
  })
})
.then(num => console.log(num)); // console.log(5) 2sec
```
<br/>

### 4. Error Handling
```
const getHen = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve("Hen"), 1000);
  });

const getEgg = hen =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${hen} => Egg`), 1000);
  });

const cook = egg =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => Fry`), 1000);
  });

getHen()
  .then(hen => getEgg(hen))
  .then(egg => cook(egg))
  .then(meal => console.log(meal)); //3sec
```
<br/>

```
const getHen = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve("Hen"), 1000);
  });

const getEgg = hen =>
  new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error(`${hen}=> Egg`)), 1000);
  });

const cook = egg =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => Fry`), 1000);
  });


getHen()
  .then(hen => getEgg(hen))
  .catch(error => {
    return `bread`;
  })
  .then(egg => cook(egg))
  .then(meal => console.log(meal))
  .catch(console.log);
```



